<?php
/*
+--------------------------------------------------------------------+
| CiviCRM version 4.6                                                |
+--------------------------------------------------------------------+
| Copyright CiviCRM LLC (c) 2004-2015                                |
+--------------------------------------------------------------------+
| This file is a part of CiviCRM.                                    |
|                                                                    |
| CiviCRM is free software; you can copy, modify, and distribute it  |
| under the terms of the GNU Affero General Public License           |
| Version 3, 19 November 2007 and the CiviCRM Licensing Exception.   |
|                                                                    |
| CiviCRM is distributed in the hope that it will be useful, but     |
| WITHOUT ANY WARRANTY; without even the implied warranty of         |
| MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.               |
| See the GNU Affero General Public License for more details.        |
|                                                                    |
| You should have received a copy of the GNU Affero General Public   |
| License and the CiviCRM Licensing Exception along                  |
| with this program; if not, contact CiviCRM LLC                     |
| at info[AT]civicrm[DOT]org. If you have questions about the        |
| GNU Affero General Public License or the licensing of CiviCRM,     |
| see the CiviCRM license FAQ at http://civicrm.org/licensing        |
+--------------------------------------------------------------------+
*/
/**
 * @package CRM
 * @copyright CiviCRM LLC (c) 2004-2015
 *
 * Generated from xml/schema/CRM/Civisocial/CivisocialEngagementaccount.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 */
require_once 'CRM/Core/DAO.php';
require_once 'CRM/Utils/Type.php';
class CRM_Civisocial_DAO_CivisocialEngagementaccount extends CRM_Core_DAO
{
  /**
   * static instance to hold the table name
   *
   * @var string
   */
  static $_tableName = 'civisocial_engagement_account';
  /**
   * static instance to hold the field values
   *
   * @var array
   */
  static $_fields = null;
  /**
   * static instance to hold the keys used in $_fields for each field.
   *
   * @var array
   */
  static $_fieldKeys = null;
  /**
   * static instance to hold the FK relationships
   *
   * @var string
   */
  static $_links = null;
  /**
   * static instance to hold the values that can
   * be imported
   *
   * @var array
   */
  static $_import = null;
  /**
   * static instance to hold the values that can
   * be exported
   *
   * @var array
   */
  static $_export = null;
  /**
   * static value to see if we should log any modifications to
   * this table in the civicrm_log table
   *
   * @var boolean
   */
  static $_log = false;
  /**
   * Twitter user id
   *
   * @var bigint
   */
  public $user_id;
  /**
   * Twitter user secreen name
   *
   * @var string
   */
  public $screen_name;
  /**
   * Twitter user old time line
   *
   * @var datetime
   */
  public $old_timeline_collected;
  /**
   * Twitter user New time line
   *
   * @var datetime
   */
  public $new_timeline_collected;
  /**
   * Twitter user old search
   *
   * @var datetime
   */
  public $old_search_collected;
  /**
   * Twitter user New search
   *
   * @var datetime
   */
  public $new_search_collected;
  /**
   * Twitter user search since
   *
   * @var bigint
   */
  public $search_since_id;
  /**
   * Old direct message sent collected
   *
   * @var datetime
   */
  public $old_dms_sent_collected;
  /**
   * direct direct message sent collected
   *
   * @var datetime
   */
  public $new_dms_sent_collected;
  /**
   * Old direct message received collected
   *
   * @var datetime
   */
  public $old_dms_received_collected;
  /**
   * direct direct message received collected
   *
   * @var datetime
   */
  public $new_dms_received_collected;
  /**
   * class constructor
   *
   * @return civisocial_engagement_account
   */
  function __construct()
  {
    $this->__table = 'civisocial_engagement_account';
    parent::__construct();
  }
  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  static function &fields()
  {
    if (!(self::$_fields)) {
      self::$_fields = array(
        'user_id' => array(
          'name' => 'user_id',
          'type' => CRM_Utils_Type::T_BIGINT,
          'title' => ts('Twitter user id') ,
          'description' => 'Twitter user id',
          'required' => true,
          'import' => true,
          'where' => 'civisocial_engagement_account.user_id',
          'headerPattern' => '',
          'dataPattern' => '',
          'export' => true,
          'default' => 'NULL',
        ) ,
        'screen_name' => array(
          'name' => 'screen_name',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => ts('screen name') ,
          'description' => 'Twitter user secreen name',
          'required' => true,
          'maxlength' => 20,
          'size' => CRM_Utils_Type::MEDIUM,
          'import' => true,
          'where' => 'civisocial_engagement_account.screen_name',
          'headerPattern' => '',
          'dataPattern' => '',
          'export' => true,
          'default' => 'NULL',
        ) ,
        'old_timeline_collected' => array(
          'name' => 'old_timeline_collected',
          'type' => CRM_Utils_Type::T_DATE + CRM_Utils_Type::T_TIME,
          'title' => ts('Old timeline') ,
          'description' => 'Twitter user old time line',
          'required' => true,
          'import' => true,
          'where' => 'civisocial_engagement_account.old_timeline_collected',
          'headerPattern' => '',
          'dataPattern' => '',
          'export' => true,
          'default' => 'NULL',
        ) ,
        'new_timeline_collected' => array(
          'name' => 'new_timeline_collected',
          'type' => CRM_Utils_Type::T_DATE + CRM_Utils_Type::T_TIME,
          'title' => ts('New timeline') ,
          'description' => 'Twitter user New time line',
          'required' => true,
          'import' => true,
          'where' => 'civisocial_engagement_account.new_timeline_collected',
          'headerPattern' => '',
          'dataPattern' => '',
          'export' => true,
          'default' => 'NULL',
        ) ,
        'old_search_collected' => array(
          'name' => 'old_search_collected',
          'type' => CRM_Utils_Type::T_DATE + CRM_Utils_Type::T_TIME,
          'title' => ts('Old search') ,
          'description' => 'Twitter user old search',
          'required' => true,
          'import' => true,
          'where' => 'civisocial_engagement_account.old_search_collected',
          'headerPattern' => '',
          'dataPattern' => '',
          'export' => true,
          'default' => 'NULL',
        ) ,
        'new_search_collected' => array(
          'name' => 'new_search_collected',
          'type' => CRM_Utils_Type::T_DATE + CRM_Utils_Type::T_TIME,
          'title' => ts('New search') ,
          'description' => 'Twitter user New search',
          'required' => true,
          'import' => true,
          'where' => 'civisocial_engagement_account.new_search_collected',
          'headerPattern' => '',
          'dataPattern' => '',
          'export' => true,
          'default' => 'NULL',
        ) ,
        'search_since_id' => array(
          'name' => 'search_since_id',
          'type' => CRM_Utils_Type::T_BIGINT,
          'title' => ts('Search since') ,
          'description' => 'Twitter user search since ',
          'required' => true,
          'import' => true,
          'where' => 'civisocial_engagement_account.search_since_id',
          'headerPattern' => '',
          'dataPattern' => '',
          'export' => true,
          'default' => 'NULL',
        ) ,
        'old_dms_sent_collected' => array(
          'name' => 'old_dms_sent_collected',
          'type' => CRM_Utils_Type::T_DATE + CRM_Utils_Type::T_TIME,
          'title' => ts('Old dms sent') ,
          'description' => 'Old direct message sent collected ',
          'required' => true,
          'import' => true,
          'where' => 'civisocial_engagement_account.old_dms_sent_collected',
          'headerPattern' => '',
          'dataPattern' => '',
          'export' => true,
          'default' => 'NULL',
        ) ,
        'new_dms_sent_collected' => array(
          'name' => 'new_dms_sent_collected',
          'type' => CRM_Utils_Type::T_DATE + CRM_Utils_Type::T_TIME,
          'title' => ts('New dms sent') ,
          'description' => 'direct direct message sent collected ',
          'required' => true,
          'import' => true,
          'where' => 'civisocial_engagement_account.new_dms_sent_collected',
          'headerPattern' => '',
          'dataPattern' => '',
          'export' => true,
          'default' => 'NULL',
        ) ,
        'old_dms_received_collected' => array(
          'name' => 'old_dms_received_collected',
          'type' => CRM_Utils_Type::T_DATE + CRM_Utils_Type::T_TIME,
          'title' => ts('Old dms received') ,
          'description' => 'Old direct message received collected ',
          'required' => true,
          'import' => true,
          'where' => 'civisocial_engagement_account.old_dms_received_collected',
          'headerPattern' => '',
          'dataPattern' => '',
          'export' => true,
          'default' => 'NULL',
        ) ,
        'new_dms_received_collected' => array(
          'name' => 'new_dms_received_collected',
          'type' => CRM_Utils_Type::T_DATE + CRM_Utils_Type::T_TIME,
          'title' => ts('New dms received') ,
          'description' => 'direct direct message received collected ',
          'required' => true,
          'import' => true,
          'where' => 'civisocial_engagement_account.new_dms_received_collected',
          'headerPattern' => '',
          'dataPattern' => '',
          'export' => true,
          'default' => 'NULL',
        ) ,
      );
    }
    return self::$_fields;
  }
  /**
   * Returns an array containing, for each field, the arary key used for that
   * field in self::$_fields.
   *
   * @return array
   */
  static function &fieldKeys()
  {
    if (!(self::$_fieldKeys)) {
      self::$_fieldKeys = array(
        'user_id' => 'user_id',
        'screen_name' => 'screen_name',
        'old_timeline_collected' => 'old_timeline_collected',
        'new_timeline_collected' => 'new_timeline_collected',
        'old_search_collected' => 'old_search_collected',
        'new_search_collected' => 'new_search_collected',
        'search_since_id' => 'search_since_id',
        'old_dms_sent_collected' => 'old_dms_sent_collected',
        'new_dms_sent_collected' => 'new_dms_sent_collected',
        'old_dms_received_collected' => 'old_dms_received_collected',
        'new_dms_received_collected' => 'new_dms_received_collected',
      );
    }
    return self::$_fieldKeys;
  }
  /**
   * Returns the names of this table
   *
   * @return string
   */
  static function getTableName()
  {
    return self::$_tableName;
  }
  /**
   * Returns if this table needs to be logged
   *
   * @return boolean
   */
  function getLog()
  {
    return self::$_log;
  }
  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  static function &import($prefix = false)
  {
    if (!(self::$_import)) {
      self::$_import = array();
      $fields = self::fields();
      foreach($fields as $name => $field) {
        if (CRM_Utils_Array::value('import', $field)) {
          if ($prefix) {
            self::$_import['al_engagement_account'] = & $fields[$name];
          } else {
            self::$_import[$name] = & $fields[$name];
          }
        }
      }
    }
    return self::$_import;
  }
  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  static function &export($prefix = false)
  {
    if (!(self::$_export)) {
      self::$_export = array();
      $fields = self::fields();
      foreach($fields as $name => $field) {
        if (CRM_Utils_Array::value('export', $field)) {
          if ($prefix) {
            self::$_export['al_engagement_account'] = & $fields[$name];
          } else {
            self::$_export[$name] = & $fields[$name];
          }
        }
      }
    }
    return self::$_export;
  }
}
